[package]
name = "rad-tools-mpc-checks-cleaner"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
clap.workspace = true
tracing.workspace = true
chrono.workspace = true
rad-tools-core = { path = "../core" }

[[bin]]
name = "mpc_checks_cleaner"
path = "src/main.rs"