[package]
name = "rad-tools-dcm-study-series-uid"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
dicom-core.workspace = true
dicom-object.workspace = true
serde.workspace = true
serde_json.workspace = true
rad-tools-core = { path = "../core" }

[[bin]]
name = "dcm_study_series_uid"
path = "src/bin/dcm_study_series_uid.rs"

