[package]
name = "rad-tools-one-way-sync"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
chrono.workspace = true

[[bin]]
name = "one-way-sync"
path = "src/main.rs"