[package]
name = "rad-tools-common"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
tracing.workspace = true
thiserror.workspace = true
dicom-object.workspace = true