[package]
name = "rad-tools-dosecheck-pdf-mv"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap.workspace = true
tracing-appender = {version = "0.2", optional = true}

[dev-dependencies]
tempfile.workspace = true

[[bin]]
name = "dosecheck_pdf_mv"
path = "src/bin/main.rs"

[[bin]]
name = "dosecheck_pdf_mv_daemon"
path = "src/bin/main_daemon.rs"

[features]
default = []
WindowsDaemon = ["dep:tracing-appender"]